import type { Version } from "./constants";

type T = { zh: string; en: string };
const l = (zh: string, en: string): T => ({ zh, en });

export interface DesignDecisionItem {
  title: T;
  why: T;
  tradeoff: T;
}

export const DESIGN_DECISIONS: Record<Version, DesignDecisionItem[]> = {
  h01: [{ title: l("让模型控制停止条件", "Let the model control stop conditions"), why: l("只要还有工具可调，agent 就应保持在循环里，而不是被外层强行截断。", "If tools are still useful, the agent should stay inside the loop instead of being forcefully cut off by outer code."), tradeoff: l("循环更强，但必须配 iteration budget 防止失控。", "The loop is more capable, but it needs an iteration budget to avoid runaway behavior.") }],
  h02: [{ title: l("schema 与 handler 分离", "Separate schema from handler"), why: l("模型读 schema，代码跑 handler，两边职责清晰，才能稳定扩工具。", "The model reads schema while code runs handlers, so responsibilities stay clear and tools scale cleanly."), tradeoff: l("注册信息更多，但主循环可以长期保持不变。", "You write more registration data, but the main loop stays unchanged over time.") }],
  h03: [{ title: l("todo 做成 agent-level tool", "Make todo an agent-level tool"), why: l("todo 修改的是 agent 自身执行状态，不是外部世界。", "todo mutates the agent's own execution state, not the outside world."), tradeoff: l("逻辑不再完全统一走注册表，但计划状态会更稳。", "The path is no longer fully uniform through the registry, but planning state becomes more stable.") }],
  h04: [{ title: l("prompt 动态组装", "Assemble prompts dynamically"), why: l("不同上下文来源要按优先级竞争 token 预算，而不是硬塞进一个长字符串。", "Different context sources must compete for token budget by priority instead of being stuffed into one long string."), tradeoff: l("实现更复杂，但 prompt 更稳定也更可维护。", "Implementation is more complex, but prompts become more stable and maintainable.") }],
  h05: [{ title: l("压缩中间历史而非直接删旧消息", "Compress middle history instead of deleting old messages"), why: l("真正重要的是保留近期工作记忆，同时把更早的路径压成摘要。", "The key is keeping recent working memory while compressing older paths into a summary."), tradeoff: l("需要额外摘要步骤，但上下文窗口可持续运行。", "It adds a summary step, but keeps the context window sustainable.") }],
  h06: [{ title: l("会话持久化优先于纯内存", "Persist sessions instead of relying on memory only"), why: l("agent 重启后仍要能恢复，不然复杂任务的连续性会断掉。", "The agent must resume after restart or complex task continuity breaks."), tradeoff: l("要处理存储结构，但换来可恢复与可检索能力。", "You must manage storage structure, but gain resumability and retrieval.") }],
  h07: [{ title: l("记忆主动 flush", "Flush memory actively"), why: l("上下文不是长期记忆，必须把值得长期保留的知识单独落盘。", "Context is not long-term memory, so durable knowledge must be written separately."), tradeoff: l("要做筛选与去重，但能避免把临时噪音写成永久知识。", "You must filter and deduplicate, but avoid turning temporary noise into permanent memory.") }],
  h08: [{ title: l("skill 注入为 user message", "Inject skills as user messages"), why: l("这样不会破坏 system prompt 前缀缓存，也更像临时操作指南。", "This preserves system-prompt prefix caching and better matches temporary operating guidance."), tradeoff: l("skill 不再拥有最高优先级，但缓存与切换更稳定。", "Skills lose top priority, but caching and switching become more stable.") }],
  h09: [{ title: l("审批门放在调度层", "Put approval at the dispatch layer"), why: l("安全策略应覆盖所有工具，而不是要求每个工具各自实现一套。", "Security policy should cover all tools instead of asking every tool to implement its own gate."), tradeoff: l("调度层更重，但安全规则更统一。", "The dispatch layer gets heavier, but safety rules stay unified.") }],
  h10: [{ title: l("失败分层处理", "Handle failure in layers"), why: l("retry、fallback、终止是不同层级的动作，混在一起会让恢复逻辑失真。", "Retry, fallback, and termination are different response layers; mixing them distorts recovery logic."), tradeoff: l("错误分支更多，但系统恢复行为更可预测。", "There are more error branches, but recovery behavior becomes predictable.") }],
  h11: [{ title: l("命令中心注册", "Centralize command registration"), why: l("一份命令定义驱动多个入口，避免 CLI 与网关端各写一份。", "One command definition should drive multiple surfaces instead of duplicating logic for CLI and gateways."), tradeoff: l("注册模型更抽象，但跨端一致性大幅提升。", "The registration model is more abstract, but cross-surface consistency improves significantly.") }],
  h12: [{ title: l("平台差异收敛在 Gateway", "Collapse platform differences into Gateway"), why: l("agent 内部不该知道 Telegram、CLI 或 HTTP 的细节。", "The agent internals should not know Telegram, CLI, or HTTP details."), tradeoff: l("入口层更厚，但核心 agent 更干净。", "The entry layer gets thicker, but the core agent stays cleaner.") }],
  h13: [{ title: l("cron job 也是完整 agent", "Treat cron jobs as full agents"), why: l("定时任务不只是执行脚本，它也需要工具、上下文和输出投递。", "A scheduled job is not just a script; it also needs tools, context, and delivery."), tradeoff: l("调度成本更高，但能力与普通 agent 对齐。", "Scheduling cost is higher, but capabilities align with normal agents.") }],
  h14: [{ title: l("hook 只做副作用", "Hooks handle side effects only"), why: l("如果 hook 能改主控制流，系统边界会迅速失控。", "If hooks can alter core control flow, system boundaries quickly collapse."), tradeoff: l("hook 能力受限，但主循环可维护性更强。", "Hooks are constrained, but the main loop remains maintainable.") }],
  h15: [{ title: l("子 agent 强调上下文隔离", "Prioritize context isolation for subagents"), why: l("delegation 的关键不是多一次调用，而是给子任务一块干净工作区。", "Delegation is not about one more call; it is about giving the subtask a clean workspace."), tradeoff: l("上下文复制与汇总更麻烦，但子任务质量更高。", "Copying and merging context is harder, but subtask quality is higher.") }],
  h16: [{ title: l("Provider 抽象先于 SDK 细节", "Provider abstraction before SDK details"), why: l("模型后端会持续变化，主循环不该被某一家 SDK 锁死。", "Backends keep changing, so the main loop should not be locked to one SDK."), tradeoff: l("适配层更多，但切模型和切平台的代价更低。", "There is more adapter code, but switching models and providers becomes cheaper.") }],
  h17: [{ title: l("MCP 工具并入原生注册表", "Merge MCP tools into the native registry"), why: l("agent 不应区分工具来自本地还是外部 server。", "The agent should not care whether a tool comes from local code or an external server."), tradeoff: l("接入前多一步握手发现，但运行时路径完全统一。", "There is an extra discovery handshake upfront, but runtime paths become fully unified.") }],
  h18: [{ title: l("插件是一等扩展机制", "Make plugins a first-class extension path"), why: l("不想靠 fork 扩展 Hermes，就必须提供官方注册面。", "If Hermes should grow without forks, it needs official registration surfaces."), tradeoff: l("核心接口要长期稳定，但生态扩展成本大幅下降。", "Core interfaces must stay stable longer, but ecosystem extension becomes much cheaper.") }],
  h19: [{ title: l("先过滤再训练", "Filter before training"), why: l("运行轨迹天然杂乱，直接送训会把噪音与坏样本一并放大。", "Runtime traces are noisy by nature; training on them directly amplifies bad samples."), tradeoff: l("数据流水线更长，但训练样本质量明显更高。", "The data pipeline gets longer, but training data quality improves substantially.") }],
};
